#include "settings_model.h"
#include "moonlight/api.h"
#include <stdio.h>
static SettingRow g_rows[kSettingRowMax];static SettingSection g_sections[kSettingSectionMax];static int g_row_count=0,g_section_count=0,g_ready=0;
static const wchar_t*r[]={L"960x540",L"960x544",L"1024x576",L"1152x648",L"1280x540",L"1280x720",L"1366x768",L"1600x900",L"1920x1080"};
static const wchar_t*f[]={L"24",L"30",L"40",L"50",L"60"};static const wchar_t*b[]={L"2000",L"4000",L"5000",L"8000",L"10000",L"15000",L"20000",L"30000"};
static const wchar_t*c[]={L"Xbox",L"PlayStation",L"Nintendo",L"Generic"};static const wchar_t*t[]={L"Off",L"DS4 Touchpad",L"Mouse Absolute",L"Tablet (Sunshine)"};static const wchar_t*k[]={L"US",L"DE",L"ES",L"FR",L"RU"};
static SettingRow base(SettingKind q,const wchar_t*l,MoonlightSettingKey key){SettingRow x={};x.kind=q;x.label=l;x.key=key;return x;}
static SettingRow tog(const wchar_t*l,MoonlightSettingKey q){return base(KIND_TOGGLE,l,q);}
static SettingRow cho(const wchar_t*l,MoonlightSettingKey q,const wchar_t*const*x,int n,int a){SettingRow z=base(KIND_CHOICE,l,q);z.choices=x;z.choice_count=n;z.arrows=a;return z;}
static SettingRow integer(const wchar_t*l,MoonlightSettingKey q,int s,int mn,int mx,int a){SettingRow z=base(KIND_INT,l,q);z.step=s;z.min_v=mn;z.max_v=mx;z.arrows=a;return z;}
static SettingRow cat(const wchar_t*l){return base(KIND_CATEGORY,l,MOONLIGHT_SETTING_COUNT);}static SettingRow note(const wchar_t*l){return base(KIND_NOTE,l,MOONLIGHT_SETTING_COUNT);}static SettingRow fixed(const wchar_t*l,const wchar_t*v){SettingRow z=base(KIND_FIXED,l,MOONLIGHT_SETTING_COUNT);z.fixed=v;return z;}
void settings_model_init(){if(g_ready)return;g_ready=1;moonlight_api_init();int i=0;
g_rows[i++]=cat(L"Stream");g_rows[i++]=cho(L"Resolution",MOONLIGHT_SETTING_RESOLUTION,r,9,1);g_rows[i++]=cho(L"FPS",MOONLIGHT_SETTING_FPS,f,5,1);g_rows[i++]=cho(L"Bitrate",MOONLIGHT_SETTING_BITRATE,b,8,0);g_rows[i++]=tog(L"Change graphical game settings for performance",MOONLIGHT_SETTING_SOPS);g_rows[i++]=tog(L"Enable reference frame invalidation",MOONLIGHT_SETTING_REF_FRAME_INVALIDATION);g_rows[i++]=tog(L"Enable stream optimization",MOONLIGHT_SETTING_STREAM_OPTIMIZATION);g_rows[i++]=tog(L"Enable VITA vblank",MOONLIGHT_SETTING_VITA_VBLANK);g_rows[i++]=tog(L"Enable frame pacer",MOONLIGHT_SETTING_FRAME_PACER);g_rows[i++]=tog(L"Enable local audio",MOONLIGHT_SETTING_LOCAL_AUDIO);
g_rows[i++]=cat(L"System");g_rows[i++]=tog(L"Enable debug log",MOONLIGHT_SETTING_DEBUG_LOG);g_rows[i++]=tog(L"Disable power save",MOONLIGHT_SETTING_DISABLE_POWER_SAVE);g_rows[i++]=tog(L"Swap X & O for Moonlight",MOONLIGHT_SETTING_SWAP_XO);g_rows[i++]=tog(L"Display streaming FPS",MOONLIGHT_SETTING_SHOW_FPS);
g_rows[i++]=cat(L"Input");g_rows[i++]=tog(L"Enable Gyroscope reporting",MOONLIGHT_SETTING_GYRO);g_rows[i++]=tog(L"Enable double tap to sprint",MOONLIGHT_SETTING_DOUBLE_TAP_SPRINT);g_rows[i++]=integer(L"Sprint double tap time",MOONLIGHT_SETTING_SPRINT_DOUBLE_TAP_TIME,50,50,500,0);g_rows[i++]=cho(L"Controller type",MOONLIGHT_SETTING_CONTROLLER_TYPE,c,4,1);g_rows[i++]=tog(L"Swap R1/L1 <-> R2/L2",MOONLIGHT_SETTING_SWAP_SHOULDERS);g_rows[i++]=integer(L"Mouse acceleration",MOONLIGHT_SETTING_MOUSE_ACCELERATION,15,0,300,1);g_rows[i++]=tog(L"Enable mapping file",MOONLIGHT_SETTING_MAPPING_ENABLED);g_rows[i++]=note(L"Configured in the original vita-moonlight.conf");g_rows[i++]=tog(L"Enable PS button capture",MOONLIGHT_SETTING_PS_BUTTON_CAPTURE);g_rows[i++]=fixed(L"Back touchscreen deadzone",L"Loaded from legacy configuration");g_rows[i++]=tog(L"Enable touchscreen special keys",MOONLIGHT_SETTING_FRONT_TOUCHZONES);g_rows[i++]=fixed(L"Touchscreen special keys",L"Loaded from legacy configuration");g_rows[i++]=cho(L"Touchscreen mode",MOONLIGHT_SETTING_TOUCHSCREEN_MODE,t,4,0);
g_rows[i++]=cat(L"Keyboard");g_rows[i++]=cho(L"Keyboard layout",MOONLIGHT_SETTING_KEYBOARD_LAYOUT,k,5,0);g_row_count=i;
g_section_count=0;for(int j=0;j<i;++j){if(g_rows[j].kind!=KIND_CATEGORY||g_section_count>=kSettingSectionMax)continue;if(g_section_count>0)g_sections[g_section_count-1].count=j-g_sections[g_section_count-1].first;g_sections[g_section_count].title=g_rows[j].label;g_sections[g_section_count].first=j+1;g_sections[g_section_count].count=i-j-1;++g_section_count;}}
int settings_model_row_count(){settings_model_init();return g_row_count;} SettingRow*settings_model_row(int i){settings_model_init();return i>=0&&i<g_row_count?&g_rows[i]:NULL;} int settings_model_section_count(){settings_model_init();return g_section_count;} SettingSection*settings_model_section(int i){settings_model_init();return i>=0&&i<g_section_count?&g_sections[i]:NULL;}
int settings_model_get_value(const SettingRow&r,int*v){return v&&r.key!=MOONLIGHT_SETTING_COUNT?moonlight_api_get_setting_value(r.key,v):-1;} int settings_model_set_value(const SettingRow&r,int v){return r.key!=MOONLIGHT_SETTING_COUNT?moonlight_api_set_setting_value(r.key,v):-1;}
static void aw(wchar_t*d,int cap,const char*s){if(cap<=0)return;int i=0;for(;s[i]&&i<cap-1;++i)d[i]=(wchar_t)s[i];d[i]=0;}
void settings_model_format_value(const SettingRow&r,wchar_t*d,int cap){if(cap<=0)return;int v=0;if(r.kind==KIND_TOGGLE){aw(d,cap,settings_model_get_value(r,&v)==0&&v?"yes":"no");return;}if(r.kind==KIND_CHOICE&&r.choices&&r.choice_count>0){if(settings_model_get_value(r,&v)){d[0]=0;return;}if(v<0)v=0;if(v>=r.choice_count)v=r.choice_count-1;const wchar_t*s=r.choices[v];int i=0;for(;s[i]&&i<cap-1;++i)d[i]=s[i];d[i]=0;return;}if(r.kind==KIND_INT){if(settings_model_get_value(r,&v)){d[0]=0;return;}char buf[32];snprintf(buf,sizeof(buf),"%d",v);aw(d,cap,buf);return;}if(r.kind==KIND_FIXED&&r.fixed){int i=0;for(;r.fixed[i]&&i<cap-1;++i)d[i]=r.fixed[i];d[i]=0;return;}d[0]=0;}
